// <auto-generated />
using System;
using HechoaMano.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HechoaMano.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240425043238_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HechoaMano.Domain.Entities.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Family");

                    b.HasData(
                        new
                        {
                            Id = new Guid("df982bf9-019c-4803-a457-6b695999c0e1"),
                            Name = "BOLSO"
                        },
                        new
                        {
                            Id = new Guid("ac7725cb-a113-462a-abb9-11a1eeb28c8a"),
                            Name = "MONEDERO"
                        },
                        new
                        {
                            Id = new Guid("bee3184d-535c-4b8d-a9a9-6fb4f0f8af86"),
                            Name = "PORTAVASO"
                        },
                        new
                        {
                            Id = new Guid("712b01f2-16c1-485b-a706-3c69e4039b04"),
                            Name = "JUEGO DE COPA"
                        },
                        new
                        {
                            Id = new Guid("0263a484-83d0-4f5b-aaa1-7139d5872d6a"),
                            Name = "JUEGO BAR BOTELLA"
                        },
                        new
                        {
                            Id = new Guid("c3b6aa5a-5a0e-447c-ba11-f59201644b3e"),
                            Name = "COPA UN TRAGO"
                        },
                        new
                        {
                            Id = new Guid("d90acb8c-ffb9-41f0-bb7a-7e19f4550bc5"),
                            Name = "COPA TEQUILERA"
                        },
                        new
                        {
                            Id = new Guid("909e82ed-0701-4a6b-8209-e514ebf21ad7"),
                            Name = "ESTUCHE"
                        },
                        new
                        {
                            Id = new Guid("9594d7b6-5493-4caf-ae3a-26e5508ccfa1"),
                            Name = "COPA MINI"
                        },
                        new
                        {
                            Id = new Guid("91200448-6687-4cba-821e-beb03101284a"),
                            Name = "LLAVERO"
                        },
                        new
                        {
                            Id = new Guid("2a0e232e-9f10-40b4-ba83-de30df9882e3"),
                            Name = "ESPEJO"
                        },
                        new
                        {
                            Id = new Guid("6e204ba0-242e-4dfa-bbd7-44faa14b4b09"),
                            Name = "BURBUJA"
                        },
                        new
                        {
                            Id = new Guid("ff3d99b5-af8f-4967-b584-bce184378be3"),
                            Name = "IMAN"
                        },
                        new
                        {
                            Id = new Guid("4cf67052-6009-40c8-a18d-a76d4309bf93"),
                            Name = "GORRA"
                        },
                        new
                        {
                            Id = new Guid("2d331347-79b7-49e1-8244-71f142d47c6c"),
                            Name = "CIGARRILLERA"
                        },
                        new
                        {
                            Id = new Guid("c228f565-b01f-4cbb-9af9-a8be668bde5a"),
                            Name = "PLATO"
                        },
                        new
                        {
                            Id = new Guid("504a1741-78a3-4d8f-957c-b8253472b1d4"),
                            Name = "DESTAPADOR"
                        });
                });

            modelBuilder.Entity("HechoaMano.Domain.Entities.FamilyType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FamilyType");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f3188b6-8ca7-482c-99af-50696bdd54d5"),
                            Name = "COLOR"
                        },
                        new
                        {
                            Id = new Guid("a36ce337-d584-430b-8f42-f42e6feb238b"),
                            Name = "TRADICIONAL"
                        });
                });

            modelBuilder.Entity("HechoaMano.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Region");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5e3f563-6285-45ce-b61c-2a07b54e2a2c"),
                            Name = "COLOMBIA"
                        },
                        new
                        {
                            Id = new Guid("2a0fa02c-1931-4652-be45-e29b7326ff95"),
                            Name = "MEDELLIN"
                        },
                        new
                        {
                            Id = new Guid("7b827de3-0669-4561-81db-e314ba753e72"),
                            Name = "CALI"
                        },
                        new
                        {
                            Id = new Guid("7813e404-a9a8-47a4-9253-4a13b1599d20"),
                            Name = "BARRANQUILLA"
                        },
                        new
                        {
                            Id = new Guid("a740e73d-b53a-4c7f-be18-a19cf12981bf"),
                            Name = "CARTAGENA"
                        },
                        new
                        {
                            Id = new Guid("0c9e8e75-8fc0-46c0-a8b7-3db0e0f5ffda"),
                            Name = "SAN ANDRES"
                        },
                        new
                        {
                            Id = new Guid("a08fc5d7-5dd9-4eea-be75-da04959dd869"),
                            Name = "SANTA MARTA "
                        },
                        new
                        {
                            Id = new Guid("2c819989-bd3d-4b6e-82df-98cc700ac6ca"),
                            Name = "GUATAPE"
                        },
                        new
                        {
                            Id = new Guid("00f98968-ea5f-4794-b713-d5cc2e353dfa"),
                            Name = "ARMENIA"
                        },
                        new
                        {
                            Id = new Guid("dd68b5f8-7137-4969-85d6-da59c68fe34e"),
                            Name = "GENERAL"
                        });
                });

            modelBuilder.Entity("HechoaMano.Domain.Entities.Size", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Size");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3800bd7c-f9f8-4e14-9aad-d29ced527d29"),
                            Name = "GRANDE"
                        },
                        new
                        {
                            Id = new Guid("72132e04-6bf2-44c3-8b49-fa289a6c72da"),
                            Name = "PEQUEÑO"
                        },
                        new
                        {
                            Id = new Guid("78f38613-e708-4ea2-9fd0-9d7bcc12477f"),
                            Name = "No 0"
                        },
                        new
                        {
                            Id = new Guid("82d3d0e8-86d7-4f08-a588-21d6ae1a1617"),
                            Name = "No 1"
                        },
                        new
                        {
                            Id = new Guid("8ffd0ad9-c046-483d-84c7-b215ee16e535"),
                            Name = "No 2"
                        },
                        new
                        {
                            Id = new Guid("6a574c0c-6b6b-4be4-8c03-6ec8f338f188"),
                            Name = "No 3"
                        },
                        new
                        {
                            Id = new Guid("2dfacc69-35c9-423e-a08d-98aad4b3afa1"),
                            Name = "MEDIANO"
                        },
                        new
                        {
                            Id = new Guid("c73fb604-7552-45d5-b5fb-989fbb9557f2"),
                            Name = "X2"
                        },
                        new
                        {
                            Id = new Guid("c98dce0c-12c6-435a-9591-bca60a3e2b14"),
                            Name = "X3"
                        },
                        new
                        {
                            Id = new Guid("86131149-6a38-418c-87f2-daa6a02a4366"),
                            Name = "X4"
                        },
                        new
                        {
                            Id = new Guid("daab74f6-0e08-43e6-a40f-056c2474d248"),
                            Name = "X6"
                        },
                        new
                        {
                            Id = new Guid("43ac00bc-c8a7-4d06-8790-d5a97ad4e60c"),
                            Name = "X5"
                        },
                        new
                        {
                            Id = new Guid("d103bf0e-c39f-479d-ab83-143048175d7a"),
                            Name = "MINI"
                        });
                });

            modelBuilder.Entity("HechoaMano.Domain.Entities.SubFamily", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SubFamily");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ecfd59c1-bf4b-4cac-9365-0993a47cec39"),
                            Name = "PIRAMIDE"
                        },
                        new
                        {
                            Id = new Guid("33127463-2b78-4e3e-9e15-daaf76920af3"),
                            Name = "TELAR"
                        },
                        new
                        {
                            Id = new Guid("fd0ad594-5276-422b-ba21-575e7fb00fd9"),
                            Name = "DOBLE APLIQUE"
                        },
                        new
                        {
                            Id = new Guid("0f5b0115-4414-4840-8a03-183e765b9b34"),
                            Name = "MEDIA LUNA"
                        },
                        new
                        {
                            Id = new Guid("6db4d206-c71d-40ef-82bb-5eae5d435563"),
                            Name = "CHIVA"
                        },
                        new
                        {
                            Id = new Guid("83953d5a-81cd-4652-9c5a-54712b32a477"),
                            Name = "SOMBRERO"
                        },
                        new
                        {
                            Id = new Guid("1edb1dc3-078b-4170-a0bb-896ed3e0e883"),
                            Name = "SERVILLETERO ROMBO"
                        },
                        new
                        {
                            Id = new Guid("f6346c1f-4829-459a-b0bf-686ba96bdf41"),
                            Name = "SERVILLETERO MORA"
                        },
                        new
                        {
                            Id = new Guid("a259d3ca-5546-4e9c-a10b-4c7d6eb57106"),
                            Name = "ESTUCHE"
                        },
                        new
                        {
                            Id = new Guid("179092b3-3ee1-43eb-a81e-e42ec359adfd"),
                            Name = "SERVILLETERO JUAN VALDES"
                        },
                        new
                        {
                            Id = new Guid("0c4b816a-c3de-48bb-b162-4f2b4d0e9dcd"),
                            Name = "SERVILLETERO CUNA"
                        },
                        new
                        {
                            Id = new Guid("8db0bb97-f4d8-482b-ab74-a122ef68d83c"),
                            Name = "UN TRAGO"
                        },
                        new
                        {
                            Id = new Guid("25eadf3c-665c-482e-8a13-9b3d42b66463"),
                            Name = "BARCO COPAS UN TRAGO"
                        },
                        new
                        {
                            Id = new Guid("2bdf07ce-39c1-4c16-9ac7-8fdccf4af4ce"),
                            Name = "FORRO CUERO"
                        },
                        new
                        {
                            Id = new Guid("62abc136-e744-4eb1-b25a-7cf8e776f75f"),
                            Name = "COLGAR CUERO"
                        },
                        new
                        {
                            Id = new Guid("582f4bca-bb05-4bf4-a833-b44e81a862d2"),
                            Name = "DISEÑO CRISTAL"
                        },
                        new
                        {
                            Id = new Guid("a7177299-67ce-4dfa-8297-75c2209b8607"),
                            Name = "DISEÑO OPALIZADA"
                        },
                        new
                        {
                            Id = new Guid("466d23e9-9e29-4c78-98f1-90592032c774"),
                            Name = "CHIVA BAR MINI"
                        },
                        new
                        {
                            Id = new Guid("a77b8975-ceaa-4d82-b3b0-e045c1044ee9"),
                            Name = "CARRETA BAR MINI"
                        },
                        new
                        {
                            Id = new Guid("d14962a2-917f-4f55-8362-9f79b629a4ef"),
                            Name = "COPA MINI"
                        },
                        new
                        {
                            Id = new Guid("be64776e-307c-4dd3-b45d-5b6ae64441c8"),
                            Name = "CORTAUÑA"
                        },
                        new
                        {
                            Id = new Guid("dfe08ea5-6722-4bcb-9e32-6ce9e69e6e44"),
                            Name = "ESPEJO"
                        },
                        new
                        {
                            Id = new Guid("75f1c417-1bfa-4dab-8cb0-c2d17bad3f97"),
                            Name = "DESTAPADOR"
                        },
                        new
                        {
                            Id = new Guid("00d9ce6f-d79f-41c8-be27-9af2e297f84c"),
                            Name = "PLACA"
                        },
                        new
                        {
                            Id = new Guid("51e4466b-31ae-48e3-96ee-d53314dceb04"),
                            Name = "CUERO"
                        },
                        new
                        {
                            Id = new Guid("3a01e83c-cd94-4d60-a886-aa05ce1bd6b2"),
                            Name = "TAGUA MULTICOLOR"
                        },
                        new
                        {
                            Id = new Guid("bc96b721-86ae-49d9-83b8-385b7116ee6d"),
                            Name = "COLLAGE"
                        },
                        new
                        {
                            Id = new Guid("42359aa0-ac34-401d-8d15-bf1f6688b6d0"),
                            Name = "BOTERO"
                        },
                        new
                        {
                            Id = new Guid("e384d0c3-f99d-44e4-a694-c0b13e201f06"),
                            Name = "HUEVO"
                        },
                        new
                        {
                            Id = new Guid("cfadbd49-6943-4c4a-82e2-d46e9f436e2a"),
                            Name = "GATO"
                        },
                        new
                        {
                            Id = new Guid("23ba186c-3793-46b8-a58c-8cd3398ff1e4"),
                            Name = "PUEBLITO PAISA"
                        },
                        new
                        {
                            Id = new Guid("97ae7023-1ddc-4c49-b1ee-c655763d343b"),
                            Name = "GUATAPE"
                        },
                        new
                        {
                            Id = new Guid("c02637a3-ae54-45e5-a012-78abba3156e8"),
                            Name = "PLATOS CERAMICA"
                        },
                        new
                        {
                            Id = new Guid("b27a54df-9f69-4361-820c-63d433b7190d"),
                            Name = "MARCO"
                        },
                        new
                        {
                            Id = new Guid("c469684c-284d-4076-93ee-b1fe178dd584"),
                            Name = "RECINA"
                        },
                        new
                        {
                            Id = new Guid("a794799b-9e72-4017-bddf-1200b3014621"),
                            Name = "RECTANGULO"
                        },
                        new
                        {
                            Id = new Guid("99478d56-10e6-4975-9b6b-459eced55226"),
                            Name = "FLORES"
                        },
                        new
                        {
                            Id = new Guid("dfbd09ed-74a1-4d82-82f7-0b16115883f2"),
                            Name = "FINAS"
                        },
                        new
                        {
                            Id = new Guid("62b65e1e-132f-4991-aa97-87f7615bb66f"),
                            Name = "BORDADA"
                        },
                        new
                        {
                            Id = new Guid("ea67017f-44b1-4769-8283-c4408273c96a"),
                            Name = "MALLA"
                        },
                        new
                        {
                            Id = new Guid("f1404373-b654-403e-b91d-9a241c0ccfbc"),
                            Name = "TINTERO"
                        },
                        new
                        {
                            Id = new Guid("e5838980-58cf-46f0-9016-848919a56f3e"),
                            Name = "METAL"
                        });
                });

            modelBuilder.Entity("HechoaMano.Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FamilyTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SellPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SizeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubFamilyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.HasIndex("FamilyTypeId");

                    b.HasIndex("RegionId");

                    b.HasIndex("SizeId");

                    b.HasIndex("SubFamilyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HechoaMano.Domain.Products.Product", b =>
                {
                    b.HasOne("HechoaMano.Domain.Entities.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HechoaMano.Domain.Entities.FamilyType", "FamilyType")
                        .WithMany()
                        .HasForeignKey("FamilyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HechoaMano.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HechoaMano.Domain.Entities.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HechoaMano.Domain.Entities.SubFamily", "SubFamily")
                        .WithMany()
                        .HasForeignKey("SubFamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");

                    b.Navigation("FamilyType");

                    b.Navigation("Region");

                    b.Navigation("Size");

                    b.Navigation("SubFamily");
                });
#pragma warning restore 612, 618
        }
    }
}
